Wayland config is here!
- DWM -> Hyprland
- Dmenu -> fuzzel
- custom bar -> eww
- and much more

NOTE: This is still a work in progress, but it was time to commit these
changes.

diff --git a/.local/bin/grimblast b/.local/bin/grimblast
--- a/.local/bin/grimblast
+++ b/.local/bin/grimblast
@@ -3,11 +3,14 @@
 ## Requirements:
 ##  - `grim`: screenshot utility for wayland
 ##  - `slurp`: to select an area
-##  - `hyprctl`: to read properties of current window
-##  - `wl-copy`: clipboard utility
+##  - `hyprctl`: to read properties of current window (provided by Hyprland)
+##  - `hyprpicker`: to freeze the screen when selecting area
+##  - `wl-copy`: clipboard utility (provided by wl-clipboard)
 ##  - `jq`: json utility to parse hyprctl output
-##  - `notify-send`: to show notifications
+##  - `notify-send`: to show notifications (provided by libnotify)
 ## Those are needed to be installed, if unsure, run `grimblast check`
+##
+## See `man 1 grimblast` or `grimblast usage` for further details.
 
 ## Author: Misterio (https://github.com/misterio77)
 
@@ -38,6 +41,10 @@ env_editor_confirm() {
 
 NOTIFY=no
 CURSOR=
+FREEZE=
+WAIT=no
+SCALE=
+HYPRPICKER_PID=-1
 
 while [ $# -gt 0 ]; do
   key="$1"
@@ -51,6 +58,29 @@ while [ $# -gt 0 ]; do
     CURSOR=yes
     shift # past argument
     ;;
+  -f | --freeze)
+    FREEZE=yes
+    shift # past argument
+    ;;
+  -w | --wait)
+    shift
+    WAIT=$1
+    if echo "$WAIT" | grep "[^0-9]" -q; then
+      echo "Invalid value for wait '$WAIT'" >&2
+      exit 3
+    fi
+    shift
+    ;;
+  -s | --scale)
+    shift # past argument
+    if [ $# -gt 0 ]; then
+      SCALE="$1" # assign the next argument to SCALE
+      shift      # past argument
+    else
+      echo "Error: Missing argument for --scale option."
+      exit 1
+    fi
+    ;;
   *)      # unknown option
     break # done with parsing --flags
     ;;
@@ -59,12 +89,12 @@ done
 
 ACTION=${1:-usage}
 SUBJECT=${2:-screen}
-FILE=${3:-$(getTargetDirectory)/$(date "+%G-%m-%d_%H-%M-%S").png}
-FILE_EDITOR=${3:-$(tmp_editor_directory)/$(date "+%G-%m-%d_%H-%M-%S").png}
+FILE=${3:-$(getTargetDirectory)/$(date -Ins).png}
+FILE_EDITOR=${3:-$(tmp_editor_directory)/$(date -Ins).png}
 
 if [ "$ACTION" != "save" ] && [ "$ACTION" != "copy" ] && [ "$ACTION" != "edit" ] && [ "$ACTION" != "copysave" ] && [ "$ACTION" != "check" ]; then
   echo "Usage:"
-  echo "  grimblast [--notify] [--cursor] (copy|save|copysave|edit) [active|screen|output|area] [FILE|-]"
+  echo "  grimblast [--notify] [--cursor] [--freeze] [--wait N] [--scale <scale>] (copy|save|copysave|edit) [active|screen|output|area] [FILE|-]"
   echo "  grimblast check"
   echo "  grimblast usage"
   echo ""
@@ -104,7 +134,14 @@ notifyError() {
   fi
 }
 
+killHyprpicker() {
+  if [ ! $HYPRPICKER_PID -eq -1 ]; then
+    kill $HYPRPICKER_PID
+  fi
+}
+
 die() {
+  killHyprpicker
   MSG=${1:-Bye}
   notifyError "Error: $MSG"
   exit 2
@@ -125,11 +162,17 @@ takeScreenshot() {
   GEOM=$2
   OUTPUT=$3
   if [ -n "$OUTPUT" ]; then
-    grim ${CURSOR:+-c} -o "$OUTPUT" "$FILE" || die "Unable to invoke grim"
+    grim ${CURSOR:+-c} ${SCALE:+-s "$SCALE"} -o "$OUTPUT" "$FILE" || die "Unable to invoke grim"
   elif [ -z "$GEOM" ]; then
-    grim ${CURSOR:+-c} "$FILE" || die "Unable to invoke grim"
+    grim ${CURSOR:+-c} ${SCALE:+-s "$SCALE"} "$FILE" || die "Unable to invoke grim"
   else
-    grim ${CURSOR:+-c} -g "$GEOM" "$FILE" || die "Unable to invoke grim"
+    grim ${CURSOR:+-c} ${SCALE:+-s "$SCALE"} -g "$GEOM" "$FILE" || die "Unable to invoke grim"
+  fi
+}
+
+wait() {
+  if [ "$WAIT" != "no" ]; then
+    sleep "$WAIT"
   fi
 }
 
@@ -138,6 +181,7 @@ if [ "$ACTION" = "check" ]; then
   check grim
   check slurp
   check hyprctl
+  check hyprpicker
   check wl-copy
   check jq
   check notify-send
@@ -155,11 +199,30 @@ elif [ "$SUBJECT" = "output" ]; then
   OUTPUT=$(hyprctl monitors -j | jq -r '.[] | select(.focused == true)' | jq -r '.name')
   WHAT="$OUTPUT"
 elif [ "$SUBJECT" = "area" ]; then
+  if [ "$FREEZE" = "yes" ] && [ "$(command -v "hyprpicker")" ] >/dev/null 2>&1; then
+    hyprpicker -r -z &
+    sleep 0.2
+    HYPRPICKER_PID=$!
+  fi
+
+  # get fade & fadeOut animation and unset it
+  # this removes the black border seen around screenshots
+  FADE="$(hyprctl -j animations | jq -jr '.[0][] | select(.name == "fade") | .name, ",", (if .enabled == true then "1" else "0" end), ",", (.speed|floor), ",", .bezier')"
+  FADEOUT="$(hyprctl -j animations | jq -jr '.[0][] | select(.name == "fadeOut") | .name, ",", (if .enabled == true then "1" else "0" end), ",", (.speed|floor), ",", .bezier')"
+  hyprctl keyword animation 'fade,0,1,default' >/dev/null
+  hyprctl keyword animation 'fadeOut,0,1,default' >/dev/null
+
   WORKSPACES="$(hyprctl monitors -j | jq -r 'map(.activeWorkspace.id)')"
   WINDOWS="$(hyprctl clients -j | jq -r --argjson workspaces "$WORKSPACES" 'map(select([.workspace.id] | inside($workspaces)))')"
   GEOM=$(echo "$WINDOWS" | jq -r '.[] | "\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"' | slurp)
+
+  # reset fade
+  hyprctl keyword animation "$FADE" >/dev/null
+  hyprctl keyword animation "$FADEOUT" >/dev/null
+
   # Check if user exited slurp without selecting the area
   if [ -z "$GEOM" ]; then
+    killHyprpicker
     exit 1
   fi
   WHAT="Area"
@@ -168,6 +231,8 @@ elif [ "$SUBJECT" = "window" ]; then
 else
   die "Unknown subject to take a screen shot from" "$SUBJECT"
 fi
+
+wait
 
 if [ "$ACTION" = "copy" ]; then
   takeScreenshot - "$GEOM" "$OUTPUT" | wl-copy --type image/png || die "Clipboard error"
@@ -201,3 +266,5 @@ else
     notifyError "Error taking screenshot with grim"
   fi
 fi
+
+killHyprpicker
